### ISSUE TITLE
抛出异常调试

### ISSUE THREAD

**Issue by zhangxiang-plct** [zhangxiang-plct/jdk8u#124]

**Comment by zhangxiang-plct** [comment]
```
Error occurred during initialization of VM
java.lang.IncompatibleClassChangeError
        at sun.reflect.Reflection.<clinit>(Reflection.java:46)
        at sun.misc.Unsafe.<clinit>(Unsafe.java:49)
        at sun.misc.SharedSecrets.<clinit>(SharedSecrets.java:48)
        at java.lang.ref.Reference.<clinit>(Reference.java:235)


Exception: java.lang.IncompatibleClassChangeError thrown from the UncaughtExceptionHandler in thread "Reference Handler"
```
